spring.application.name=Lundeborg-Saunagus

# Mysql Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3607/${MYSQL_DATABASE:Lundeborg-Saunagus-db}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${MYSQL_USER:Freja}
spring.datasource.password=${MYSQL_PASSWORD:secret}

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health

